import random

turt = [
    "Turtles are the only pets that make you feel fast.",
    "My turtle ran away yesterday. I’m giving him until next month to come back.",
    "Turtles don’t have trust issues, they *have shells*.",
    "If I were a turtle, I’d also stay home all day. Rent’s free.",
    "Ever seen a turtle run? Exactly. That’s their whole personality.",
    "My turtle and my Wi-Fi have the same speed.",
    "Turtles are proof you can be slow and still win sometimes.",
    "If a turtle loses its shell, is it naked or homeless?",
    "Turtles don’t ghost people, they just slowly disappear.",
    "A turtle’s idea of cardio is blinking twice.",
    "Turtles live for 100 years because stress never catches up to them.",
    "I asked my turtle for life advice. He blinked once. I think he said chill.",
    "Turtles don’t rush. The world just moves too fast.",
    "Every turtle looks like it has taxes due.",
    "Turtles are just rocks with opinions.",
    "You think you’re introverted? My turtle hasn’t left his room since 2018.",
    "Turtles move like they’re buffering.",
    "A turtle’s favorite quote: ‘I’m not slow, I’m just on turtle time.’",
    "Turtles don’t do mornings. Or afternoons. Or evenings.",
    "If turtles could text, you’d get a reply next year.",
    "Turtles are just dinosaurs that gave up on ambition.",
    "When life gets hard, turtles say ‘nah’ and hide.",
    "Turtles prove that silence is powerful. And kind of awkward.",
    "My turtle looked at me, blinked, and went back in. Mood.",
    "If turtles could drive, every road would be a traffic jam.",
    "Turtles don’t need therapy. They have shells for emotional support.",
    "You can’t rush greatness. Or turtles.",
    "Turtles are what happens when evolution decides to take a nap.",
    "Turtles don’t argue. They just slowly walk away mid-conversation.",
    "A turtle at top speed is still not in a hurry.",
    "Turtles invented minimalism. One outfit for life.",
    "When turtles are late, no one’s surprised. It’s expected.",
    "Turtles live long because they literally can’t stress fast enough.",
    "Turtles make sloths look like caffeine addicts.",
    "If turtles had TikTok, their videos would all be loading.",
    "Turtles don’t run from problems—they outlive them.",
    "You think your life’s slow? My turtle’s still deciding where to go since breakfast.",
    "Turtles don’t chase love. They wait till it bumps into them.",
    "Every turtle looks like it knows something you don’t.",
    "Turtles move slower than my motivation on Mondays.",
    "Turtles don’t do drama—they’re too busy existing.",
    "My turtle’s workout routine: one step, nap, repeat.",
    "Turtles prove that having boundaries can be stylish.",
    "If a turtle races a snail, it’s basically Formula 1.",
    "Turtles don’t need to glow up—they’re born ancient and wise.",
    "Turtles never have FOMO. They literally miss everything.",
    "A turtle’s life goal? Don’t die. So far, undefeated.",
    "Turtles don’t get road rage—they *are* roadblocks.",
    "Turtles sleep like they just paid rent.",
    "Turtles never get lost. They carry their GPS with them.",
    "Turtles don’t do trends. They outlive them."
]

def turtle():
    joke = random.choice(turt)
    print(joke)
